apiVersion: v1
kind: Secret
metadata:
  name: elixir-secret
type: Opaque
data:
  GIT_API: fill
  CB_USER: fill
  CB_PASS: fill
  JENKINS_USER: fill
  JENKINS_PASS: fill
  TRELLO_KEY: fill
  TRELLO_TOKEN: fill


